name: Upload Flat File to BigQuery

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: testproject-459116
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate with service account
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > key.json
          gcloud auth activate-service-account --key-file=key.json

      - name: Upload to BigQuery
        run: |
          bq load \
            --autodetect \
            --source_format=CSV \
            flatfiletesting.customer \
            ./flatfile.txt

      - name: Clean up key file
        run: rm key.json